### PR TITLE
Update AndroidBuild.java

### PR DESCRIPTION
**Pull request by pegleg999**
Change project target to 13 to enable Admob

### CODE REVIEW

**Comment by boubpopsyteam** [comment]
Not good, Min SDK have to stay to level 10 / gingerbread.
http://developer.android.com/guide/topics/manifest/uses-sdk-element.html#ApiLevels

(+ for the records, your patch would have needed to change the comments at least ;)

**Comment by pegleg999** [comment]
Can the code be updated so the variable is derived from the manifest xml? 

Sent from Samsung Mobile

-------- Original message --------

**Comment by pegleg999** [comment]
Can the variable be updated via the xml manifest instead of being hard coded?

Sent from Samsung Mobile

-------- Original message --------

**Comment by boubpopsyteam** [comment]
Processing itself don't need it as Android is backward compatible.
(that is you don't need to target your current version, an equal or lower is enough)

**Comment by pegleg999** [comment]
From my research, this doesnt seem to correct, I'm trying to implement
Admob, and all the forums go back to changing the target SDK to a 14 to
enable some functionality

**Comment by boubpopsyteam** [comment]
If admob require lvl14, do it for you. It's not processing related so don't change processing. :)

**Comment by pegleg999** [comment]
Hmm.. not sure how to build the source code from scratch including the
android plug in

**Comment by benfry** [comment]
Err, no... This would set the minimum Android version to 3.2 for anything produced with Processing. We're not ready to do that.

**Pull request closed without merging**
